### ISSUE TITLE
Drag and drop of notebooks and notes to Favorites panel not working

### ISSUE THREAD

**Issue by jb261** [benji300/joplin-favorites#3]
When I drag a notebook from sidebar or note from note list to the Favorites panel, I get a rectangular indicator (to indicate that the mouse is over an acceptable drop point, as opposed to the circle with slash indicating unacceptable drop point), but the notebook or note are not added to Favorites. 

Not a big deal since right-click menu on notebook or note allows adding to Favorites, but figured I'd report it since it's not behaving as per README documentation.

> Joplin 1.7.3 (prod, win32)

If you cannot replicate, let me know and I'll check logs.

**Comment by benji300** [comment]
Currently drag&drop of notebooks or notes works only if you drag them onto the 'FAVORITES' (as stated in the README) title of the panel. Which has to be enabled in the settings. This was my intention to keep the implementation simple.
But you just gave me an idea. Maybe I could also just add the whole container for the drop event. So dragging "external" items just over the panel to add them... I will check it.

> "...as opposed to the circle with slash indicating unacceptable drop point..."

Do you know how this behavior could be implemented? Currently the problem is, that the favorites also accept the drop event (to rearrange them internally). So I don't know how force the unacceptable behavior in case it is not another favorite.

**Comment by jb261** [comment]
OK, I misinterpreted the README:  "Drag notebooks and notes from sidebar or note list directly to favorites"
Might be worth clarifying that sentence to specify the drop should be over Favorites title, which as you note does work fine.

I do think drag and drop onto the entire panel is more intuitive given how other software typically operates in this regard, but I don't think it's worth a lot of extra effort on your part. With both right click context menu and drag/drop to Favorites title, you've provided two means to add to Favorites, so drag/drop to panel is a very marginal enhancement.

No, sorry, I do not know how to technically implement. I do think it's more important to preserve drag/drop rearranging inside the Favorites panel than it is to add drag/drop notebook or note from outside Favorites panel to anywhere in the Favorites panel, since we already have two methods to add these items to the panel.

**Comment by benji300** [comment]
The sentence from the README is indeed a little unfortunate. I will correct it.

"_I do think drag and drop onto the entire panel is more intuitive given how other software typically operates in this regard, but I don't think it's worth a lot of extra effort on your part._"
I'm going to check it out though, I'm curios to see if and how it might work. 😉

**Comment by benji300** [comment]
Behavior will be changed in v1.2.0
